config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
  validates :name, :presence => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  validates :description, :presence => true

  scope(:done, -> do
    where({:done => true})
  end)

  scope(:not_done, -> do
    where({:done => false})
  end)

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @tasks = Task.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list= List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def create
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = "List successfully added!"
      redirect_to lists_path
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end


  private
  def list_params
    params.require(:list).permit(:name)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @task = @list.tasks.new
  end

  def show
    @list = List.all
    @tasks = Task.all
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.new(task_params)
    if @task.save
      redirect_to list_path(@task.list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
  end

  def update
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
      if @task.update(task_params)
        redirect_to lists_path
      else
        render :edit
      end
    end

  def destroy
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to list_path(@task.list)
  end

  private
  def task_params
    params.require(:task).permit(:description, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= image_tag "banner.jpg", :class => "img-responsive", :id => "header" %>
    <%= flash[:alert] %>
    <%= flash[:notice] %>

<div class="container">
    <%= yield %>
</div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= render "layouts/errors", :object => @list %>

<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control" %>
  <%= f.submit :class => "btn btn-success" %>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit list</h1>

<%= render "form" %>

app/views/lists/index.html.erb
<% content_for(:title, "Your To Do App") %>

<h1>Lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

<%= link_to "Add New List", new_list_path, :class => "btn btn-info" %>


<h1>To Do Tasks</h1>
<ul>
  <% @lists.each do |list| %>
  <% list.tasks.not_done().each do |task| %>
    <li>
      <%= task.description %>
      <%= form_for [list, task] do |f| %>
      <%= f.hidden_field(:done, :value => true) %>
      <%= f.submit 'mark done', :class => "btn btn-success" %>
  <% end %>
    </li>
  <% end %>
  <% end %>
</ul>


<h1>Done Tasks</h1>
<ul>
  <% @lists.each do |list| %>
  <% list.tasks.done().each do |task| %>
    <li>
      <%= task.description %>
      <%= form_for [list, task] do |f| %>
      <%= f.hidden_field(:done, :value => false) %>
      <%= f.submit 'mark not done', :class => "btn btn-warning" %>
  <% end %>
    </li>
  <% end %>
  <% end %>
</ul>

app/views/lists/new.html.erb
<h1>New list!</h1>

<%= render "form" %>

app/views/lists/show.html.erb
<% content_for(:title, "List | To Do") %>

<h1><%= @list.name %></h1>

<% if @list.tasks.any? %>
  <h4>Here are the tasks for this list:</h4>

  <ul>
    <% @list.tasks.each do |task| %>
    <li>
      <%= task.description %>
      <%= link_to "Edit Task", edit_list_task_path(@list, task) %>
      <%= link_to "Delete Task", list_task_path(@list, task),
      :data => {:confirm => "You sure?",
        :method => "delete"} %>
    </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no tasks yet!</p>
<% end %>

<p><%= link_to 'Add New Task', new_list_task_path(@list) %></p>
<p><%= link_to "Edit List", edit_list_path(@list) %></p>
<p><%= link_to "Delete List", list_path(@list),
                  :data => {:confirm => "You sure?",
                          :method => "delete"} %></p>

<p><%= link_to "Return to lists", lists_path %></p>

app/views/tasks/_form.html.erb
<%= render "layouts/errors", :object => @task %>

<%= form_for [@list, @task] do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.hidden_field(:done, :value => false) %>
  <%= f.submit %>
<% end %>

app/views/tasks/complete_tasks.html.erb
<h1>Done Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%= task.description %> </li>
  <%end%>
</ul>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render "form" %>

app/views/tasks/new.html.erb
<h1>New task for <%= @list.name %></h1>

<%= render 'form' %>